include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
 rules:
  constant_identifier_names: false
  lines_longer_than_80_chars: false
  public_member_api_docs: false
  avoid_positional_boolean_parameters: false
  use_build_context_synchronously: false

analyzer:
 exclude:
  - "build/**"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.es.dart"
 errors:
  invalid_annotation_target: false
