name: client
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.18.0
  dio: ^5.4.1
  envied: ^0.5.3
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.10
  intl: ^0.19.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.4
  simple_animations: ^5.0.2
  socket_io_client: ^2.0.3+1
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.11
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  image_path_android: "assets/images/icon-android.png"
  image_path_ios: "assets/images/icon-ios.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"
  macos:
    generate: true
    image_path: "assets/images/icon-ios.png"
  windows:
    generate: true
    image_path: "assets/images/icon-android.png"
