version: "1.0"

services:
 server:
  image: capstone/server
  ports:
   - "5179:5179"
   - "5197:5197"
  env_file:
   - .env
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:5179/health"]
   interval: 1m30s
   timeout: 30s
   retries: 5
   start_period: 30s

 postgres:
  image: postgres
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123456789
   POSTGRES_DB: capstone
  volumes:
   - postgres-data:/var/lib/postgresql/data

 clickhouse:
  image: clickhouse/clickhouse-server
  ports:
   - "8123:8123"
   - "9000:9000"
  volumes:
   - clickhouse-data:/var/lib/clickhouse

volumes:
 postgres-data:
 clickhouse-data:
